Feature/17 북마크 관련 기능
wlsh44/job-finder pull request #21
Opened 2022-07-13 12:58 UTC by wlsh44

2022-07-17 06:24 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/ResponseDto.java
> +}
generic 사용하셨네요 👍

2022-07-17 06:26 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/advice/BookmarkControllerAdvice.java
> +        log.info(e.getMessage());
@wlsh44 
error의 메시지를 남기기 위한거면 `log.info` 보다는  `log.error`가 더 낫지 않을까요?

2022-07-17 06:28 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/NewCategoryRequestDto.java
> +    }
@wlsh44 
다른 Dto의 `toEntity`도 마찬가지인데요.
만약 `User`에 `null`이 들어오면 어떻게 되나요?
`null`이 들어왔을때에 대한 처리를 해줘야 할거 같아요.

2022-07-17 06:32 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/converter/PlatformConverter.java
> +}
@wlsh44 
음.. 요고 `@Enumerated(EnumType.STRING)` 로 사용하면 되지 않나요?

2022-07-17 06:32 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/converter/PlatformConverter.java
> +        return attribute.koreaName();
@wlsh44 
column에 한글로 저장을 하는건가요? 한글로 저장하시는 이유가 있을까요?

2022-07-17 06:33 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Recruit.java
> +    private Platform platform;
@wlsh44 
enum타입을 한글로 컬럼에 저장을 하면서 좀 복잡해지는거 같은데요.
한글로 저장하시는 이유가 있을까요?
enum타입을 string으로 저장하면 `@Enumerated(EnumType.STRING)` 를 사용해서 간단히 가져갈수 있을거 같은데요.

2022-07-17 06:35 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Recruit.java
> +    private List<Tag> tags = new ArrayList<>();
@wlsh44 
`@ManyToMany`는 가능하면 사용하지 않으시는게 좋아요.
`M:N` 이라면 중간에 테이블을 하나 더 만들어서 `1:N` 관계로 풀어주는게 좋을듯 합니다.

2022-07-17 06:40 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Category.java
> +)
@wlsh44 
이전에 말씀드렸듯이 `table ddl`을 따로 두고, uniqueConstraints와 같은 어노테이션은 지우는게 어떨까 싶습니다.

2022-07-17 06:44 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Recruit.java
> +    private LocalDate dueDate;
@wlsh44 
Java8 이후에 `LocalDate`나 `LocalDateTime`의 경우, `columnDefinition`을 따로 안정해줘도 됩니다.
그리고, 이것도 마찬가지로 `ddl로 테이블을 먼저 생성하면` 굳이 `columnDefinition`이 필요 없어집니다.

2022-07-17 06:45 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Recruit.java
> +    private LocalDate dueDate;
@wlsh44 
https://vladmihalcea.com/whats-new-in-jpa-2-2-java-8-date-and-time-types/

2022-07-17 06:45 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Recruit.java
> +    private LocalDate dueDate;
@wlsh44 
java8 이전과 이후에 jpa가 시간관련해서 어떻게 바뀌었는지 찾아보세요.

2022-07-17 06:46 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Tag.java
> +    private List<Recruit> recruits = new ArrayList<>();
@wlsh44 
`@ManyToMany` 는 사용하면 안좋아요.

2022-07-17 06:48 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/user/User.java
> +    private LocalDateTime createdAt;
@wlsh44 
`createdAt` 은 최초 만들어진 이후에 업데이트가 되면 안되는 컬럼 같은데요.
이럴때는 `@Column(updatable = false)` 를 사용할수 있습니다.

https://wonit.tistory.com/484

2022-07-17 06:53 UTC, f-lab-mammouth commented on src/main/resources/templates/job-find/recruits.html
> +        var recruitDtoList = [[ ${recruitDtoList} ]]
@wlsh44 
- `js` 에 대해서도 기본적인 문법은 알고 있으면 추후 도움이 될것같아 코멘트 남깁니다.
  - `var`는 es6 이후부터는 가능하면 사용 안하는게 좋습니다.
  - `const`, `let` 둘 중에 하나를 사용하시는게 좋습니다. (자세한건 한번 찾아보세요)
    - `const` : 변하지 않는 변수
    - `let` : 변할수 있는 변수
   
만약, `var`, `const`, `let` 이 세가지가 어떤 history를 가지고 있는지 알고 싶으시면, 아래 키워드들로 검색해보세요.
- es5, es6
- js var과 호이스팅

2022-07-17 06:57 UTC, f-lab-mammouth commented on src/main/resources/templates/user/bookmark-list.html
> +    <script type="text/javascript" th:src="@{/js/bookmark.js}"></script>
@wlsh44 
`<script type="text/javascript" ... ></script>` 는 가능하면 `<head></head>`에 넣지 마시고, `</body>` 태그 바로 윗쪽에 위치시키는게 좋습니다.
`<head>..</head>` 에는 css나 기타 메타태그들을 위치시키고, js는 닫히는 </body> 태그 바로 상단에 위치시키면 페이지 렌더링 속도가 향상됩니다.

키워드 : js script 위치

2022-07-17 06:57 UTC, f-lab-mammouth commented on src/main/resources/templates/user/bookmark-list.html
> +    <div th:replace="fragment/head.html :: fragment-head"></div>
@wlsh44 
`head.html` 에 `jquery js` 파일이 위치할텐데 요것도 가능하면 </body> 바로 위로 위치시키는게 좀 더 렌더링 속도에 효과적입니다 :)

2022-07-17 06:59 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Category.java
> +    private User user;
@wlsh44 
`ddl로 테이블 생성` 하면 referencedColumnName은 지울수 있을듯 합니다.

2022-07-17 07:03 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/repository/CategoryRepository.java
> +    List<Category> findAllByUser(User user);
@wlsh44 
보통 `findAll` 은 사용 안하는게 좋습니다.
만약 `category`숫자가 엄청나게 많을 경우 성능 이슈가 생길수 있습니다.

해결 방안은 크게 두개정도 있겠네요.
- `category` 숫자를 제한 (ex. 한사람당 최대 카테고리 생성 갯수 xx개 제한)
- `Pagenation`으로 return

2022-07-17 07:05 UTC, f-lab-mammouth commented on src/main/resources/static/js/bookmark.js
> +}
@wlsh44 
- `semicolon`이 있는 부분도 있고, 없는 부분도 있는데 통일 시켜주는게 좋습니다.
- js 특성상, es6부터는 `semicolon을 사용하지 않아도 된다` vs `사용해야 한다` 두가지 의견이 갈리는데요. 개인적으로는 `semicolon`을 붙여주는게 좀 더 직관적인것 같습니다.

2022-07-17 07:10 UTC, f-lab-mammouth requested changes
@wlsh44 
고생하셨습니다.
코멘트 남긴것들 쭉 한번 보시고 수정하면서 궁금한점 있으시면 슬랙 메시지 주세요.

저번 멘토링때 말씀드린것처럼 `ddl script`를 만들어서 `jpa`를 통한 테이블생성 대신 `ddl script`를 통해 테이블을 생성하는 방식으로 바꿔보세요. 그리고, `entity`에서 `테이블 생성 관련 옵션 (ex. referencedColumn, UniqueConstraint, etc)` 은 삭제해주시면 `entity`가 좀 더 가독성이 좋아질것 같습니다.

js에 대한 코멘트도 남겼는데요. 관심이 있으시면 코멘트 참고해서 좀 더 찾아보시고, 시간 부족하거나 관심 없으시면 그냥 한번 보고 넘기시면 됩니다.

2022-07-26 13:40 UTC, f-lab-mammouth commented on create.sql
> +    INSERT INTO `recruit_tag` (`recruit_id`, `tag_id`) VALUES ('4', '1');
@wlsh44 
`ddl`과 `dml`에 대해 찾아보시면 좋을거 같아요.
그리고, ddl과 dml 파일을 나눠주시면 좋을듯 합니다 :)

2022-07-26 13:43 UTC, f-lab-mammouth commented on create.sql
> +    INSERT INTO `recruit_tag` (`recruit_id`, `tag_id`) VALUES ('4', '1');
@wlsh44 
이전에 말씀드린것처럼 기업마다 다르겠지만, 
대기업의 경우 대부분 real에 테이블을 생성할떄 DBA에게 `ddl` 을 전달하게 됩니다.
만약 위와 같이 `sql` 을 전달하게 되면 의도치않게 테스트 데이터가 들어가게 되겠죠 :)

2022-07-26 13:46 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/BookmarkController.java
> +    private static final int PAGE_OFFSET = 1;
@wlsh44 
static을 항상 제일 윗쪽에 두시는걸 추천드려요

2022-07-26 13:49 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/BookmarkController.java
> +        BookmarkPageDto bookmarkPageDto = bookmarkService.findAllBookmarkByCategory(user, categoryId, pageable);
@wlsh44 
`페이징` 을 하는데 method명에 `all`이 들어간게 좀 이상한거 같아요.
모든 category를 다 가져올때에만 `all`을 쓰는게 맞을거 같아요 :)

2022-07-26 13:50 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/BookmarkController.java
> +        BookmarkPageDto bookmarkPageDto = bookmarkService.findAllBookmarkByCategory(user, categoryId, pageable);
@wlsh44 
현재는 데이터가 많이 없어서 이렇게 구현해도 문제가 없겠지만,
데이터가 수십만건, 수백만건이 되면 성능상에 이슈가 생길거에요 :)
관련해서 아래 링크 참고해보세요.

참고 : https://jojoldu.tistory.com/530

2022-07-26 13:55 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/advice/BookmarkControllerAdvice.java
> +}
@wlsh44 
`categoryException`, `bookmarkException`, `tagException` 은 `exception` 클래스만 다르고 response가 똑같은거 같은데요. 
추후 달라질 가능성때문에 일부러 해놓으신거면 상관없지만, 만약 추후 달라질일이 없다면 하나의 메서드로 처리 가능합니다 :) 

```java
@ExceptionHandler({
  Exception1.class,
  Exception2.class,
  Exception3.class
})
```

2022-07-26 13:58 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/CategoryResponseDto.java
> +        }
@wlsh44 
`null` 인 경우에는 `NullPointException` 이나 아니면 다른 customException을 띄우는게 좋지 않을까요?
`illegalArgumentException`은 좀 애매한 느낌이 있어서..

2022-07-26 14:02 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/TagDto.java
> +}
@wlsh44 
다른것들은 `requestDto`, `responseDto`로 나뉘어져 있는데요.
요 `TagDto` 는 어떨때 쓰이는거죠..?

2022-07-26 14:03 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/TaggingRequestDto.java
> +}
@wlsh44 
`TagDto`와 `TaggingRequestDto` 두 클래스의 이름만 보고서는 차이점을 알기가 힘들것 같아요

2022-07-26 14:03 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/UnTagRequestDto.java
> +}
@wlsh44 
`TaggingRequestDto`와 반대의 의미라면 `UnTaggingRequestDto`가 되야할거 같아요.

2022-07-26 14:04 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/UnTagRequestDto.java
> +}
@wlsh44 
명명할때도 일관적으로 할수있도록 신경쓰면 좋을거 같아요 :)

2022-07-26 14:06 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/recruit/Tag.java
> +    private Long id;
@wlsh44 
`@GeneratedValue` 를 한줄 아래로 내리면 가독성이 좋을거 같아요

2022-07-26 14:07 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/entity/user/User.java
> +@EntityListeners(AuditingEntityListener.class)
@wlsh44 
`Audit`의 경우, 지금은 `User`에서만 사용할지 몰라도 추후 다른 `Entity`에서도 사용할수 있을거 같은데요.
관련해서 한번 구글링 해보시면 좋을듯 합니다.
상속을 통해 여러 클래스에 적용하는 방법이 있습니다 :)

2022-07-26 14:12 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/repository/RecruitRepository.java
> +    Page<Recruit> findByUserAndCategory_Id(User user, Long categoryId, Pageable pageable);
@wlsh44 
조건이 많아지면 `camel-case` 룰도 안지켜지고 메서드명을 읽기도 힘들어지는데요.
이럴때는 `JPQL` 이나  `QueryDSL`  등을 사용해서 메서드명을 좀 더 간단히 가져갑니다.
`QueryDSL`은 세팅 및 공부해야할게 좀 많아서 우선 패스하고 가능하면 `JPQL`이나 `@Query` 어노테이션을 사용해서 `nativeQuery`를 사용하는 방법을 공부해보셔도 좋을거 같아요.
그러면, `arguments`가 다른 `findRecruit` 메서드를 여러개 만들수 있겠죠.

2022-07-26 14:14 UTC, f-lab-mammouth commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
👍

2022-07-26 14:17 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/user/BookmarkService.java
> +    }
@wlsh44 
요고는 `@Transactional` 안붙인 이유가 있을까요?

2022-07-26 14:18 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/user/BookmarkService.java
> +    }
@wlsh44 
`category.getRecruits().forEach(tagService::deleteAllRecruitTag)`에서 만약 `recruits`가 수십만건일 경우에 어떤 문제가 있을까요?

2022-07-26 14:20 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/user/BookmarkService.java
> +    }
@wlsh44 
요 메서드도 `@Transactional` 이 없어도 되나요?? 만약 `tagService.deleteAllRecuritTag(bookmark)`는 성공했는데 `recruitService.unbookmark(bookmark)` 가 실패한다면..?

2022-07-26 14:20 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/user/BookmarkService.java
> +    }
@wlsh44 
마찬가지로 `@transactional` 없어도 될까요?

2022-07-26 14:23 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/user/RecruitService.java
> +    }
@wlsh44 
`페이징`을 한다면 `all` 키워드는 뺴는게 좋을거 같아요

2022-08-16 03:37 UTC, f-lab-mammouth commented on src/main/resources/application.properties
> +#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=ddl.sql
👍

2022-08-16 03:38 UTC, f-lab-mammouth commented on src/main/resources/application-docker.properties
> +spring.jpa.properties.hibernate.use_sql_comments=true
@wlsh44 
일반적으로 `docker`용 `properties`를 따로 만들지는 않습니다 :)

2022-08-16 03:41 UTC, f-lab-mammouth commented on src/main/resources/application-docker.properties
> +spring.jpa.properties.hibernate.use_sql_comments=true
@wlsh44 
추가로 말씀드리면, 실무에서는 `db`의 경우 `docker`로 올리지 않습니다.
다시 말해, `docker`나 `docker-compose`로 `db`를 구성하는 경우는 `local`, `test` 와 같은 개발환경 정도로 보시면 될듯합니다.

2022-08-16 03:43 UTC, f-lab-mammouth commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker", "app.jar"]
@wlsh44 
저번 멘토링때 같이 실습하면서 말씀드린것처럼 `Dockerfile`을 통해 빌드 + 실행 모두 될수있도록 구성하는게 좋을거 같아요 :)

2022-08-16 03:46 UTC, f-lab-mammouth requested changes
@wlsh44 
고생하셨습니다.
docker 부분 관련 코멘트 보시고 수정하시면 좋을거 같아요 :)

2022-08-17 07:29 UTC, wlsh44 commented on src/main/resources/application-docker.properties
> +spring.jpa.properties.hibernate.use_sql_comments=true
넵 참고하겠습니다!
지금은 로컬이랑 도커랑 디비 세팅이 달라서 우선은 이런 식으로 진행하겠습니다..!

2022-08-17 09:25 UTC, f-lab-mammouth commented on Dockerfile
> +ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=docker", "job-finder-0.0.1-SNAPSHOT.jar"]
@wlsh44 
와우.. 깔끔하네요. 👍

2022-08-17 09:27 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/advice/BookmarkControllerAdvice.java
> +    }
@wlsh44 
`java17` 의 `switch` 도 고려해보시면 좋을거 같아요 :) 
아래 링크는 java7 => java17 까지 `switch` 문의 변화에 관련된 내용입니다.

참고 : https://medium.com/@javatechie/the-evolution-of-switch-statement-from-java-7-to-java-17-4b5eee8d29b7

2022-08-17 09:28 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/bookmark/BookmarkPageDto.java
> +}
@wlsh44 
`private` 을 안붙인 이유가 있을까요?

2022-08-17 09:33 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/service/JobKoreaJobFindServiceTest.java
> +})
@wlsh44 
👍  성능 고려하시는 부분 굿이네요

2022-08-17 09:34 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/service/user/CategoryServiceTest.java
> +    }
@wlsh44 
👍

2022-08-17 09:35 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/service/user/CategoryServiceTest.java
> +}
@wlsh44 
이제 mocking test 도 잘하시네요 👍

2022-08-17 09:37 UTC, f-lab-mammouth commented
@wlsh44 
local intellij 에서 application 실행시킬때 docker도 같이 뜨길 원한다면 아래 링크 참고해보세요 :) 
참고 : https://jojoldu.tistory.com/510

2022-08-17 09:45 UTC, f-lab-mammouth approved these changes
👍 
고생많으셨습니다.
테스트케이스 짜는것도 이전에 비해 많이 늘으신거 같고, commit 단위도 잘게 쪼개는 방법도 이제 아시는거 같고. 아주 좋습니다.

2022-08-24 02:16 UTC, merged