Feature/2 잡코리아 크롤링 구현
wlsh44/job-finder pull request #4
Opened 2022-04-06 09:48 UTC by wlsh44

2022-04-09 04:01 UTC, f-lab-mammouth commented on build.gradle
> +    implementation 'org.springframework:spring-web:5.3.18'
@wlsh44 
`spring-web:$version` 대신 `spring-boot-starter-web` 을 사용하시는걸 추천드려요.
혹시 `spring-web:$version` 을 사용하신 이유가 있을까요?

2022-04-09 04:04 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/Location.java
> +        this.koName = koName;
`koName` 만 봐서는 정확히 어떤 이름을 뜻하는지 직관적이지 않은 느낌인데요.
`district` 정도로 하면 어떨까요?

2022-04-09 04:07 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/PayType.java
> +}
@wlsh44 
`jobtype`, `location`, `paytype` 은 `jobkorea`에서 이미 정해진걸 가져다 쓰신거죠?
예를 들어서, `annual`의 `code`가 `1` 인건 jobkorea의 룰?? 이라고 보면 될까요? 

만약 그렇다면 요런 정보들을 코멘트로 남겨주시면 좋을거 같아요 :)

2022-04-09 05:22 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/CareerType.java
> +}
@wlsh44 
요런 타입?? 종류를 `util` 패키지에 넣은 이유가 있을까요?

2022-04-09 05:25 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/JobKoreaConst.java
> +}
@wlsh44 
`Constant`를 만드는 방법이 여러가지가 있는데요.
`properties` 파일에 이런 정보 (ex. jobkorea에 대한 정보) 를 정의하고 스프링부트가 해당 정보들을 객체에 담아주는 방식으로 작성해보시면 좋을거 같습니다.

참고 키워드 : `@ConfigurationProperties`

2022-04-09 05:28 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/JobKoreaCrawlerServiceUtil.java
> +}
@wlsh44 
이 객체의 `관심사` 는 결국 `DetailedSearchDto` 에 있는 필드를 가공해서 return해주는 역할인거 같은데요.
`util` 성 클래스로 만들기보다는 `DetailedSearchDto` 객체에 있는게 더 어울리지 않을까 생각되네요.

2022-04-09 05:28 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/util/jobkorea/PayType.java
> +}
@wlsh44 
역시나 `util` 패키지에 있어야하는게 맞는지 고민해보시면 좋을거 같아요

2022-04-09 05:30 UTC, f-lab-mammouth requested changes
@wlsh44 
테스트 코드 외에 다시 생각해보실만한 부분들에 대해 피드백 드렸습니다 :) 
테스트 코드 관련해서는 `slack`에 코멘트 드릴게요

2022-04-18 11:55 UTC, f-lab-mammouth commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
@wlsh44 
`starter` 와 `일반 library` 의 차이점은 뭘까요?

2022-04-18 11:58 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/JobFinderApplication.java
> +@EnableConfigurationProperties(JobKoreaConfig.class)
@wlsh44 
만약 `JobKoreaConfig.class` 와 같이 `@ConfigurationProperties` 형식의 클래스가 수십, 수백개가 된다면 여기에 다 일일이 적어줘야 할까요?

2022-04-18 11:59 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/CrawlerService.java
> +    Document crawling(DetailedSearchDto dto);
@wlsh44 
메서드는 `동사` 형태로 사용하는게 좋을거 같습니다.
`crawling` 보다는 `crawl` 처럼 동사로 하는게 어떨까요?

2022-04-18 12:01 UTC, f-lab-mammouth commented on src/main/resources/application.properties
> +jobkorea.delimiter=
@wlsh44 
아직 값을 안넣어준거죠?

2022-04-18 12:03 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerServiceTest.java
> +@TestPropertySource("classpath:application-test.properties")
@wlsh44 
아래 테스트들은 `unit test`에 가까워서 굳이 `@EnableConfigurationProperties` 와 `@TestPropertySource` 가 필요없을거 같은데, 혹시 사용한 이유가 있을까요?

2022-04-18 12:05 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +public class JobKoreaQueryParamGenerator {
@wlsh44 
다른 사이트에서도 `QueryParamGenerator` 가 필요할수 있지 않을까요?

2022-04-18 12:06 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/enums/PayType.java
> +    }
@wlsh44 
생성자가 `public` 이 아닌 이유가 있나요?

2022-04-18 12:11 UTC, f-lab-mammouth requested changes
@wlsh44 
`JobKoreaCrawlerService`로 `CrawlerService` 인터페이스를 구현하도록 수정했고 기존에 `xxxUtils` 로 되어있는 부분을 `JobKoreaQueryParamGenerator` 빈으로 만들었는데요.

`Service` 만 인터페이스로 두면 추후에 다른 사이트들이 추가될때 `확장에 열려있다고` 볼 수 있을까요?
지금 상황에서 코드 짜는걸 멈추고 아래와 같은 상황을 고려해보세요.

`기획자` :  "새로운 사이트 (xxx) 도 크롤링을 해야할거 같아요!"

2022-04-18 12:12 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/JobFinderApplication.java
> +@EnableConfigurationProperties(JobKoreaConfig.class)
- https://javacan.tistory.com/entry/springboot-configuration-properties-class

2022-04-25 10:45 UTC, f-lab-mammouth commented on .gitignore
> +*dev*
@wlsh44 
소소한 팁인데 저는 최초 프로젝트 세팅시에 https://www.toptal.com/developers/gitignore 사용해서 .gitignore 를 작성합니다.

2022-04-25 10:51 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +        queryParams.append(searchTextParam).append(locationParam).append(careerParam).append(jobParam).append(payParam).append(pageNumParam);
@wlsh44 
개인 취향이긴 한데, 저는 `append(str)` 를 한줄에 하나씩 두는게 가독성이 좋아보이는거 같아요.

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerService.java
> +    private final JobKoreaQueryParamGenerator paramGenerator;
@f-lab-mammouth 
`ParmaGenerator` 라는 구조를 적용해보다가 추후에 추가될 모든 `ParamGenerator`가 각각의 `CrawlerService`에 기능적으로 아주 의존적인 것 같아서 `interface`화 하지 않고 바로 추가를 했는데 어떻게 생각하시나요?

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +    public String toQueryParams(DetailedSearchDto dto) {
@f-lab-mammouth 
원래 `dto`에 있던 메서드인데 `ParamGenerator`가 생기면서 책임을 이쪽으로 옮기는 방법으로 바꿔봤습니다.
그러면서 든 궁금증이 있는데 `dto`는 단순히 데이터를 옮기는 책임을 넘어 어느 역할까지 해야하는지 궁금합니다!

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +package flab.project.jobfinder.service.crawler.generator;
@f-lab-mammouth 
`ParamGenerator`를 `service`패키지에 넣었는데 이처럼 `Service`가 안붙은 `Component`들의 패키지 위치에 대해 어떻게 생각하시는지 궁금합니다. 이번에 찾아보면서 패키지 이름을 `service`라고 지으면 내부 클래스명을 `Service`로 지어야될 것 같다는 강박이 생겨 `application`으로 짓는다는 글도 봐서 궁금증이 생겼습니다. 🤔
제가 알고있기로는 `service` 층은 비즈니스 로직을 담고있고 `ParamGenerator` 또한 `Crawler`에 속하는 비즈니스 로직이라 `service`안에 넣었는데 제가 잘못 알고있는건지 또는 더 정형화된 방법이 있을까요?

2022-04-25 10:52 UTC, wlsh44 commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
`일반 라이브러리`는 단순히 기능을 제공해준다면 `starter`는 공통적으로 사용되는 여러 `라이브러리`들이 충돌 없이 의존성을 가질 수 있게 해준다고 알고 있습니다.

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/JobFinderApplication.java
> +@EnableConfigurationProperties(JobKoreaConfig.class)
안그래도 궁금증이 생겼었는데 `@Configuration`을 통해 `Component`로 등록하면 됐었네요!

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/enums/PayType.java
> +    }
`enum`은 `public`생성자를 쓰지 못하는 것으로 알고 있습니다. 사실상 `enum`은 단순한 상수를 발전시켜 만든 것이기 때문에 `complie`단계에서 미리 하나의 인스턴스를 생성하고 싱글톤으로 관리합니다. 그렇기 때문에 추가적으로 인스턴스를 생성할 일이 없어 `public`생성자를 쓸 일이 없다고 생각합니다.

2022-04-25 10:52 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/CrawlerService.java
> +    Document crawling(DetailedSearchDto dto);
수정했습니다!

2022-04-25 10:52 UTC, wlsh44 commented on src/main/resources/application.properties
> +jobkorea.delimiter=
dev 설정파일을 따로 만들어서 그 안에 값을 넣어주는 방식으로 처리하고있습니다.

2022-04-25 10:52 UTC, wlsh44 commented on src/test/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerServiceTest.java
> +@TestPropertySource("classpath:application-test.properties")
설정파일도 같이 테스트해보려고 여러가지 해보다가 마지막에 빼먹은 것 같습니다ㅠㅠ 삭제했습니다.

2022-04-25 11:01 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/ParseDto.java
> +}
@wlsh44 
`date` 를 `String` 으로 받아야 하나요?
`LocalDateTime` 이나 기타 다른 `date` 관련 타입으로 받으면 좀 더 좋을거 같아요.

2022-04-25 11:08 UTC, f-lab-mammouth requested changes
@wlsh44 
각 파일에 달기 애매한 feedback들은 여기에 적겠습니다 :) 
- `service.perser` 패키지 네이밍 오타 있습니다
- `ParserService` 와 `ParseHanlder`가 어떤 차이인지 잘 모르겠습니다.
  - `naming` 만 봐서는 위 두가지가 각각 어떤 책임을 갖고 있는지 잘 모르겠습니다.
  - `parser` 와 `parserService`는 어떤 차이가 있을까요? 일반적으로 `parser`라는 명칭을 많이 사용합니다. 네이밍이 어려울땐 관련된 오픈소스 라이브러리를 보는것도 좋은 방법입니다.
- 현재까지 구현된것들의 결과물을 한눈에 파악하기가 힘듭니다.
  - `MVC (model - view - controller)` 로 구현해서 view를 통해 간단한 결과물이라도 볼수 있도록 구현하면 좋을거 같습니다 :)

2022-04-25 11:09 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +package flab.project.jobfinder.service.crawler.generator;
@wlsh44 
요 부분은 저번 멘토링 시간때 설명 드렸던것 같습니다 :)

2022-04-25 11:12 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +    public String toQueryParams(DetailedSearchDto dto) {
@wlsh44 
가능하면 `dto` 자체는 데이터를 `layer` to `layer` 로 옮기기 위한 형태로 사용하는게 좋다고 생각합니다.
getter, setter, data 변환 정도의 로직은 `dto`에 포함되어도 좋을듯 합니다. (반대로 이런 로직이 `service`로 들어가는게 더 이상하니까요)
만약 너무 복잡한 로직이 `dto`에 들어간다면 해당 로직을 하나의 독립적인 `책임` 으로 보고 클래스를 분리하는게 좋을듯 합니다.

2022-04-25 11:13 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerService.java
> +    private final JobKoreaQueryParamGenerator paramGenerator;
@wlsh44 
이전 멘토링 시간에 말씀 드렸듯이 여러가지를 고려해보시고 판단하면 될듯 합니다.
- 추후 변화가 없을듯 하다 ( = interface 없이 클래스를 사용)
- 추후 변화, 확장이 있을 가능성이 있다 ( = interface로 미리 분리)
- 아직 확실치 않고 일정이 촉박 ( = 우선 클래스 사용, 추후 필요에 따라 다시 interface로 뽑고 리팩토링)

2022-04-25 11:16 UTC, f-lab-mammouth commented
@wlsh44 
`enum`의 가시성에 `public`을 사용하지 못한다는걸 저도 처음 알았네요 :) 
매번 ide를 사용해서 습관적으로 사용하다보니 캐치를 못하고 있었습니다.
좋은정보 감사합니다!

https://github.com/wlsh44/job-finder/pull/4#discussion_r853933726

2022-04-25 18:34 UTC, wlsh44 commented on .gitignore
> +*dev*
다음 프로젝트 세팅 때 참고하겠습니다!

2022-04-25 18:35 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/dto/ParseDto.java
> +}
피드백 받은 후 `LocalDate`로 수정하던 도중에 상시채용 으로 올라오는 경우가 있어서 일단은 `String`으로 가는 방식으로 정했습니다.

2022-04-26 02:39 UTC, writer0713 commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +        Executor executor = Executors.newFixedThreadPool(totalPage);
@wlsh44 
아래 글을 보고 수정해야 할 부분이 있는지 생각해보면 좋을거 같아요
https://www.baeldung.com/java-8-parallel-streams-custom-threadpool#beware-of-the-memory-leak

2022-05-02 14:29 UTC, f-lab-mammouth commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
@wlsh44 
+ springboot의 버전에 맞는 `starter` 버전을 알아서 맞춰줍니다.
요 부분이 springboot의 장점 중 하나입니다 :)

2022-05-02 14:36 UTC, f-lab-mammouth commented on src/main/resources/application.properties
> +jobkorea.platform=
@wlsh44 
`local` 에서 테스트 (ex. 멘토 혹은 추후 github에서 pull 받은 사람) 하기 위해서 이 파일에도 적을 필요가 있을거 같습니다

2022-05-02 14:38 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/controller/JobFinderControllerTest.java
> +    JobFinderController jobFinderController;
@wlsh44 
`jobFinderController` 는 사용이 안되는거 같은데 지워도 되지 않을까요?

2022-05-02 14:42 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGeneratorTest.java
> +}
@wlsh44 
test 실패하는거 같아요

```java
expected: "stext=%EC%9B%B9+%EC%84%9C%EB%B9%84%EC%8A%A4&local=I010%2CB150&payType=1&payMin=4000"
 but was: "stext=%EC%9B%B9+%EC%84%9C%EB%B9%84%EC%8A%A4&local=I010%2CB150&payType=1&payMin=4000&Page_No=1"
```

2022-05-02 15:06 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/parser/JobKoreaParserService.java
> +}
@wlsh44 
각각의 `parseXXX` 부분에서 `NPE` 처리가 전혀 안되어 있네요.
예를 들어, [link](https://www.jobkorea.co.kr/Search/?stext=spring) 로 검색하면 간혹 `JobType`이 없는 경우가 있는데 이럴때 `NPE` 발생합니다.

현재 각 `parseXXX` 메서드들은 `무조건 해당 태그가 존재한다` 라는 가정하에 짜여져 있는데요.
존재하지 않을 경우에 대한 처리가 필요할듯 합니다.

그리고, 테스트시에는 랜덤한 url을 생성하여 테스트해야 잘 동작하는지 확인이 가능할거 같은데요.
랜덤한 test를 위해 url을 어떻게 생성하면 좋을지도 같이 생각해보세요

2022-05-02 15:08 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/parser/JobKoreaParserService.java
> +}
@wlsh44 
개인적으로 실무를 하며 항상 느끼는 점은 경력이 쌓일수록 `구현`하는 실력은 대부분 비슷하게 느는것 같습니다.
대략 3,4년차 이후부터는 `테스트`, `아키텍처`, `에러 발생 최소화` 등 `세심함`에서 큰 차이가 나게 됩니다.

2022-05-02 15:16 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +}
@wlsh44 
메서드명들이 너무 모호합니다.
`find`, `parsePage`, `asyncFind`.
메서드명만 봐서는 정확히 무슨일을 하는지 잘 모르겠습니다.

2022-05-02 15:20 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +}
@wlsh44 
수십 ~ 수백개의 페이지를 한번에 가져오려고 하다보니 `CompletableFuture`를 사용한것 같은데요.
이보다는 페이징 처리나 더 불러오기 방식으로 구현하는게 나을것 같습니다.

2022-05-07 13:29 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +                            .replaceAll("[^0-9]", "");
@wlsh44 
`pageNumStr`으ㄹ 찾는 요 부분을 하나의 메서드로 만들수 있을거 같아요.

2022-05-07 13:31 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +        return Integer.parseInt(pageNumStr) / 20 + 1;
@wlsh44 
- 그리고, 위에서 만든 메서드를 호출할때 해당 메서드에서 `int` 형으로 반환을 하도록 하면 좀 더 `getTotalPage` 메서드가 깔끔해질수 있을거 같아요.
- `20` 이라는 숫자만 봐서는 정확히 무엇을 뜻하는지 모르니 `static 변수` 로 선언하고 사용하는게 좋을거 같아요 (ex. RECRUIT_COUNT_PER_PAGE`)

2022-05-07 13:32 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +//        }
@wlsh44 
사용 안하는 코드는 항상 제거해주세요 :)

2022-05-07 13:35 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +        }
@wlsh44 
`Controller` 에서는 `요청`을 받아서 `service`로 전달해주는 역할을 하되, 정확히 어떤 `service` 객체를 사용하는지는 모르도록 작성하는게 좋을거 같습니다.

이런 경우 `팩토리 패턴` 을 사용하면 좀 더 코드가 깔끔해지고 책임을 적절하게 분리할수 있습니다 :) 

참고 : https://readystory.tistory.com/117

2022-05-07 13:37 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/RecruitPageDto.java
> +    private List<RecruitDto> list;
@wlsh44 
`list` 라는 명명이 `자료구조 list` 를 의미하는걸로 착각할수도 있을거 같네요.
`recruits` 라던가, 혹은 이전 과제에서 말씀 드렸던 `wrapper Class`를 하나 만들어도 좋을거 같네요.

2022-05-07 13:38 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/RecruitPageDto.java
> +}
@wlsh44 
`java17` 부터 `record` 라는 기능이 생겼는데요.
한번 어떤 기능을 하는지 찾아보시면 좋을거 같습니다 :)

2022-05-07 13:40 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +        model.addAttribute("dto", dto);
@wlsh44 
`dto` 라는 명명은 너무 광범위한듯 보여요. 좀 더 명확하게, 범위를 축소시켜서 지어주세요.

2022-05-07 13:41 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +        model.addAttribute("list", list);
@wlsh44 
`list`도 너무 명명이 광범위 합니다.

2022-05-07 13:41 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +        model.addAttribute("dto", dto);
@wlsh44 
요것도 마찬가지.

2022-05-07 13:43 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/RecruitDto.java
> +}
@wlsh44 
`java 17` 의 `record` 는 `@Builder`를 대신할수 있을까요?

2022-05-07 13:45 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/enums/Location.java
> +    }
@wlsh44 
```java
public static Map<String, String> toMap() {
    return Arrays.stream(values())
            .collect(Collectors.toUnmodifiableMap(Location::district, Location::name));
}
```

2022-05-07 13:46 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/enums/Location.java
> +    }
@wlsh44 
최대한 `stream` 을 통해 `최종결과`를 도출해내도록 해보세요.
다른 `enum`에도 `toMap()` 메서드가 있다면 한번 직접 바꿔보세요.

2022-05-07 13:48 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +    }
@wlsh44 
로직만 봐서는 정확히 어떤 의미인지 모르겠는데, `4` 가 의미하는게 뭔가요?
만약 다른 개발자가 봤을때 이해하기 힘들만한 로직이 있다면 (가능하면 로직을 이해하도록 짜는게 좋지만),
주석이라도 달면 좋을거 같습니다.

2022-05-07 13:51 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerService.java
> +    }
@wlsh44 
`IOException`이 발생하면 `catch` 부분에서 로그를 찍고 `null` 을 리턴하는데,
그럼 이 메서드 호출하는쪽에서 결국 `NPE` 가 발생할거 같네요.

2022-05-07 13:55 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +        Optional.ofNullable(career.getCareerMax()).filter(x -> !x.isEmpty()).ifPresent(x -> params.append("&careerMax=").append(x));
@wlsh44 
`lambda` 사용하실때 변수명을 `x`, `y` 요런거 사용하시기보다는 명확한 변수명을 주시는게 추후에 가독성이 더 좋아집니다.
ex. `careerType -> ...`

2022-05-07 13:55 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +        Optional.ofNullable(pay.getPayMax()).filter(x -> !x.isEmpty()).ifPresent(x -> params.append("&payMax=").append(x));
@wlsh44 
마찬가지로 변수명 좀 더 명확히

2022-05-07 13:58 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/parser/JobKoreaParserService.java
> +    }
@wlsh44 
`isNull` 보다는 아래처럼 사용하는게 일반적인거 같긴한데 참고만 하세요 ㅎㅎ 
```java
if (etcElement == null) {
  return "";
}

return etcElement.text();
```

2022-05-07 13:58 UTC, f-lab-mammouth commented on src/main/resources/static/index.html
> +</html>
@wlsh44 
index에서 form으로 이동하는 링크를 넣어주면 좀 더 편할거 같아요

2022-05-07 13:59 UTC, f-lab-mammouth commented on src/main/resources/templates/form.html
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
@wlsh44 
`resources/css/bootstrap.min.css`가 있는데 `cdn`을 사용하신 이유가 있을까요? 
`cdn`을 사용했을때의 장단점이 무엇이 있을까요?

2022-05-07 14:00 UTC, f-lab-mammouth commented on src/main/resources/templates/recruits.html
> +    <link rel="stylesheet" href="../css/bootstrap.min.css">
@wlsh44 
bootstrap을 두번 로드하고 있네요

2022-05-07 14:02 UTC, f-lab-mammouth commented on src/main/resources/templates/recruits.html
> +    <link rel="stylesheet" href="../css/bootstrap.min.css">
@wlsh44 
각 페이지에서 `<head>` 부분을 중복해서 작성하다 보니 이런 실수가 나온거 같아요.
이런 실수를 줄이기 위해선 어떤 해결책이 있을까요? 

키워드 : `fragment`

2022-05-07 14:05 UTC, f-lab-mammouth commented on src/main/resources/templates/recruits.html
> +                    <a th:href="${recruit.url}" th:text="${recruit.title}"></a>
@wlsh44 
링크를 클릭하면 `새로운 창` 을 띄워주는게 좀 더 좋은 유저인터페이스가 될거 같아요 :) 
키워드 : `html target`

2022-05-07 14:10 UTC, f-lab-mammouth commented on src/test/java/flab/project/jobfinder/controller/JobFinderControllerTest.java
> +                                            .build();
@wlsh44 
보통 이런 `테스트를 위한 객체` 들은 `@BeforeEach` 가 선언된 메서드 내부에서 생성하도록 합니다.

2022-05-08 10:44 UTC, wlsh44 commented on src/test/java/flab/project/jobfinder/controller/JobFinderControllerTest.java
> +                                            .build();
변경했습니다!

2022-05-08 10:44 UTC, wlsh44 commented on src/main/resources/templates/recruits.html
> +                    <a th:href="${recruit.url}" th:text="${recruit.title}"></a>
`target` 적용 했습니다.

2022-05-08 10:44 UTC, wlsh44 commented on src/main/resources/templates/recruits.html
> +    <link rel="stylesheet" href="../css/bootstrap.min.css">
두 번 로드하고 있는 줄은 몰랐네요..
`fragment` 방식으로 수정했습니다.

2022-05-08 10:47 UTC, wlsh44 commented on src/main/resources/templates/form.html
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
직접 파일을 불러왔을 때 `bootstrap`이 적용이 되지 않아 해결 방법을 찾다가 위와 같은 방법을 알게 되었습니다!

2022-05-08 10:57 UTC, wlsh44 commented on src/main/resources/templates/form.html
> +    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
사실 `cdn`에 대해 이런 방식이 있는 줄만 알고 그 외에는 전혀 몰라 찾아봤습니다.

`cdn`을 적용하게 되면 방문자가 이 서비스에 대해 캐시를 한 상태라면 웹 브라우저를 로딩하는데 속도가 빨라집니다.
또한 쉽게 서비스의 버전을 관리할 수 있으며 트래픽을 분산시켜 부하를 막아줄 수 있다고 합니다.

하지만 오프라인에서는 위의 서비스를 이용할 수 없는 단점이 있고 개발, 디버깅할 때 어려움을 겪을 수 있습니다.
저같은 경우에는 `bootstrap`의 사용법에 대해 잘 몰라 다운받았던 `bootstrap`파일을 삭제한 후 class를 적용할 때 이름도 헷갈려 개발 속도가 더 느려지기도 했습니다.
그 외에도 서비스를 사용하는 웹 사이트의 보안 문제 등이 있는 것 같습니다.

2022-05-08 10:57 UTC, wlsh44 commented on src/main/resources/static/index.html
> +</html>
추가했습니다.

2022-05-08 10:58 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/parser/JobKoreaParserService.java
> +    }
저도 왜 `isNull()`을 사용했는지 잘 모르겠어서 변경했습니다😂

2022-05-08 10:58 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/generator/JobKoreaQueryParamGenerator.java
> +        Optional.ofNullable(pay.getPayMax()).filter(x -> !x.isEmpty()).ifPresent(x -> params.append("&payMax=").append(x));
람다 식 변수 명에 관한 부분 전부 수정했습니다

2022-05-08 10:59 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/crawler/JobKoreaCrawlerService.java
> +    }
이 부분은 검증 로직을 만들 때 추가하겠습니다!

2022-05-08 11:01 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +    }
4는 페이지들의 중간을 의미합니다.
나중에 상수로 바꾸려고 했는데 그냥 올려버렸네요😂

pagination에 관한 부분은 로직으로 이해하는게 힘들 것 같다는 생각이 들어 주석도 추가했습니다.

2022-05-08 11:01 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/enums/Location.java
> +    }
수정했습니다.

2022-05-08 11:25 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/controller/JobFinderController.java
> +        }
팩토리 패턴 적용 했습니다!
그리고 switch 문을 없애기 위해 `Map`을 추가했습니다

2022-05-08 11:49 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/dto/RecruitPageDto.java
> +}
전에 `calculator` 만들면서 `IntelliJ`에서 제가 만든 클래스를 `record`로 바꿀 수 있다고 하길래 간단하게 찾아본 적이 있었습니다.

그런데 생긴지 얼마 되지 않아서 그런지는 몰라도 `record`를 사용한 예제를 본 적이 없어서 바꾸지는 않았습니다.

멘토님께서는 `record`기능에 대해 어떻게 생각하시나요?

2022-05-08 11:54 UTC, wlsh44 commented on src/main/java/flab/project/jobfinder/dto/RecruitDto.java
> +}
`record`는 기본적으로 모든 맴버 변수를 갖는 생성자를 만들어주는 것으로 알고 있습니다.

그렇기 때문에 `@Builder`패턴이 나온 이유를 생각하면 지금처럼 생성자에 들어갈 파라미터가 많은 경우에는 `@Builder`를 대신하지 못한다는 생각이 듭니다.

또한 `@Builder` 패턴은 값을  `optional`하게 넣어줄 수 있는 장점 또한 갖고 있어서 이런 경우에는 더욱 더 대신하기 힘들 것 같습니다.

2022-05-14 12:09 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/dto/RecruitPageDto.java
> +}
@wlsh44 
저도 실무에서는 아직 사용해본적이 없습니다 :) 
lombok에 비해서 아직은 기능이 부족한면이 있는것 같습니다.
우선은 `record`라는 키워드가 `java17` 부터 있다는걸 인지해두면 좋을거 같아요

2022-05-14 12:13 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +        return Platform.JOBKOREA;
👍

2022-05-14 12:21 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/enums/Location.java
> +    }
@wlsh44 
`static`으로 선언한 이유가 있나요?

2022-05-14 12:21 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +    }
👍

2022-05-14 12:22 UTC, f-lab-mammouth commented on src/main/java/flab/project/jobfinder/service/JobKoreaJobFindService.java
> +    }
@wlsh44 
수정하기 전 코드처럼 `4` 와 같이 쓰이는 녀석들을 `magic number` 라고 부릅니다.
최대한 이런 `magic number`는 변수에 할당하여 사용하는게 가독성에 좋습니다 :)

2022-05-14 12:23 UTC, f-lab-mammouth approved these changes
고생하셨습니다! 👍 
merge 하시면 될거같아요!

2022-05-14 14:27 UTC, merged

2022-05-21 14:09 UTC, writer0713 commented on src/main/java/flab/project/jobfinder/dto/ParseDto.java
> +}
@wlsh44 
뒷북이지만, 요런 케이스에 대해서는 `코멘트` 로 남겨주면 좋을거 같아요.
그래야 히스토리 관리가 되서.

2022-05-21 14:12 UTC, writer0713 commented on src/main/resources/templates/recruits.html
> +                    <a th:href="${recruit.url}" th:text="${recruit.title}"></a>
@wlsh44 
지금은 백엔드에 집중해야 하는 시기이니 우선 백엔드에 하시고,
나중에 시간되실때 기본적인 html 속성들과 js의 개념들도 공부해두시면 좋습니다 :) 

백엔드 개발자가 결국엔 fe 개발자와 함께 일해야하기 때문에 fe에 대해서도 많이 알면 알수록 커뮤니케이션이 쉬워집니다